version: "3.1"
services:
    db:
        image: mysql:5.7
        platform: linux/amd64
        container_name: mysql-wordpress
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_USER: wordpress
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - vol_db:/dump:/docker-entrypoint-initdb.d
            - vol_db:/conf:/etc/mysql/conf.d
            - vol_db:/var/lib/mysql
        networks:
            - wpsite
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        links: 
            - db:db
        ports:
            - 4282:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test

        networks:
            - wpsite

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - '4283:80'
        restart: always
        volumes: 
          - vol_public:/var/www/html
        environment:
            WORDPRESS_DB_HOST: mysql-wordpress
            WORDPRESS_DB_NAME: dbname
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: test
                   
        networks:
            - wpsite
networks:
    wpsite:            
volumes:
    vol_public:
    vol_db:
